Ini, TOML
[passwords]
admin = "Energy2026!"
lead = "ProjectLead123"

[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/1SjStdhep_n9B-Fu9yYjI8DB_ncSiRZHkqYbLyRg5evQ/edit?usp=sharing"
